<?php

return [
    'instaFilters' => [
        'file' => 'instafilters',
        'description' => '',
        'properties' => [
            'tpl' => [
                'type' => 'textfield',
                'value' => '@INLINE <img src="[[+src]]" alt="[[+alt]]" [[+classes]]>',
            ],
            'input' => [
                'type' => 'textfield',
                'value' => '',
            ],
            'alt' => [
                'type' => 'textfield',
                'value' => '',
            ],
            'classes' => [
                'type' => 'textfield',
                'value' => '',
            ],
            'filter' => [
                'type' => 'list',
                'options' => [
                    ['text' => 'Normal', 'value' => 'normal'],
                    ['text' => '1977', 'value' => '1977'],
                    ['text' => 'Aden', 'value' => 'aden'],
                    ['text' => 'Amaro', 'value' => 'amaro'],
                    ['text' => 'Ashby', 'value' => 'ashby'],
                    ['text' => 'Brannan', 'value' => 'brannan'],
                    ['text' => 'Brooklyn', 'value' => 'brooklyn'],
                    ['text' => 'Charmes', 'value' => 'charmes'],
                    ['text' => 'Clarendon', 'value' => 'clarendon'],
                    ['text' => 'Crema', 'value' => 'crema'],
                    ['text' => 'Dogpatch', 'value' => 'dogpatch'],
                    ['text' => 'Earlybird', 'value' => 'earlybird'],
                    ['text' => 'Gingham', 'value' => 'gingham'],
                    ['text' => 'Ginza', 'value' => 'ginza'],
                    ['text' => 'Hefe', 'value' => 'hefe'],
                    ['text' => 'Helena', 'value' => 'helena'],
                    ['text' => 'Hudson', 'value' => 'hudson'],
                    ['text' => 'Inkwell', 'value' => 'inkwell'],
                    ['text' => 'Kelvin', 'value' => 'kelvin'],
                    ['text' => 'Juno', 'value' => 'juno'],
                    ['text' => 'Lark', 'value' => 'lark'],
                    ['text' => 'Lo-Fi', 'value' => 'lofi'],
                    ['text' => 'Ludwig', 'value' => 'ludwig'],
                    ['text' => 'Maven', 'value' => 'maven'],
                    ['text' => 'Mayfair', 'value' => 'mayfair'],
                    ['text' => 'Moon', 'value' => 'moon'],
                    ['text' => 'Nashville', 'value' => 'nashville'],
                    ['text' => 'perpetua', 'value' => 'perpetua'],
                    ['text' => 'Poprocket', 'value' => 'poprocket'],
                    ['text' => 'Reyes', 'value' => 'reyes'],
                    ['text' => 'Rise', 'value' => 'rise'],
                    ['text' => 'Sierra', 'value' => 'sierra'],
                    ['text' => 'Skyline', 'value' => 'skyline'],
                    ['text' => 'Slumber', 'value' => 'slumber'],
                    ['text' => 'Stinson', 'value' => 'stinson'],
                    ['text' => 'Sutro', 'value' => 'sutro'],
                    ['text' => 'Toaster', 'value' => 'toaster'],
                    ['text' => 'Valencia', 'value' => 'valencia'],
                    ['text' => 'Vesper', 'value' => 'vesper'],
                    ['text' => 'Walden', 'value' => 'walden'],
                    ['text' => 'Willow', 'value' => 'willow'],
                    ['text' => 'X-Pro II', 'value' => 'xpro-ii'],
                ],
                'value' => 'normal',
            ],
            'toPlaceholder' => [
                'type' => 'combo-boolean',
                'value' => false,
            ],
        ],
    ],
];